// This file is auto-generated by scripts/generate-types.ts
// Do not edit manually.

export enum ActivityAction {
  ADDED = "ADDED",
  REMOVED = "REMOVED",
  UPDATED = "UPDATED",
  CREATED = "CREATED",
}

export enum ActivityType {
  COMMENT = "COMMENT",
  ATTACHMENT = "ATTACHMENT",
  STATUS_CHANGE = "STATUS_CHANGE",
  PRIORITY_CHANGE = "PRIORITY_CHANGE",
  ASSIGNEE_CHANGE = "ASSIGNEE_CHANGE",
  CYCLE_CHANGE = "CYCLE_CHANGE",
  DEPARTMENT_CHANGE = "DEPARTMENT_CHANGE",
  DUE_DATE_CHANGE = "DUE_DATE_CHANGE",
  TITLE_CHANGE = "TITLE_CHANGE",
  DESCRIPTION_CHANGE = "DESCRIPTION_CHANGE",
  TAG_CHANGE = "TAG_CHANGE",
  CREATED = "CREATED",
  PARENT_CHANGE = "PARENT_CHANGE",
}

export enum CycleStatus {
  PLANNED = "PLANNED",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  ON_HOLD = "ON_HOLD",
  NOT_ACTIVE = "NOT_ACTIVE",
}

export enum TaskPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum TaskStatus {
  TODO = "TODO",
  IN_PROGRESS = "IN_PROGRESS",
  REVIEW = "REVIEW",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum UserDepartment {
  SALES = "SALES",
  ADMIN = "ADMIN",
  DESIGNER = "DESIGNER",
  MANAGER = "MANAGER",
  MARKETING = "MARKETING",
  SUPPORT = "SUPPORT",
  IT = "IT",
  HR = "HR",
  FINANCE = "FINANCE",
  LEGAL = "LEGAL",
  OPERATIONS = "OPERATIONS",
  RESEARCH = "RESEARCH",
  SALES_SUPPORT = "SALES_SUPPORT",
  ECOMMERCE = "ECOMMERCE",
}

export enum UserRole {
  USER = "USER",
  ADMIN = "ADMIN",
  SUPERADMIN = "SUPERADMIN",
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export interface Company {
  code: string;
  created_at: string | null;
  id: string;
  name: string;
  updated_at: string | null;
}

export interface CompanyCode {
  code_hash: string;
  company_id: string | null;
  created_at: string | null;
  expires_at: string | null;
  id: string;
  is_active: boolean | null;
  company?: Company | null;
}

export interface Cycle {
  company_id: string | null;
  created_at: string | null;
  created_by: string | null;
  description: string | null;
  end_date: string | null;
  id: string;
  is_archived: boolean | null;
  name: string;
  start_date: string | null;
  status: CycleStatus;
  updated_at: string | null;
  company?: Company | null;
  creator?: Profile | null;
}

export interface Department {
  company_id: string | null;
  created_at: string;
  id: string;
  name: string;
  company?: Company | null;
}

export interface Profile {
  avatar_url: string | null;
  company_id: string | null;
  created_at: string;
  department: UserDepartment | null;
  email: string | null;
  full_name: string | null;
  id: string;
  location: string | null;
  phone: string | null;
  position: string | null;
  role: UserRole;
  status: UserStatus;
  updated_at: string | null;
  company?: Company | null;
}

export interface TaskActivity {
  action: ActivityAction;
  company_id: string | null;
  created_at: string | null;
  id: string;
  metadata: unknown | null;
  new_value: unknown | null;
  old_value: unknown | null;
  task_id: string;
  type: ActivityType;
  user_id: string | null;
  company?: Company | null;
  task?: Task | null;
  user?: Profile | null;
}

export interface TaskComment {
  content: string;
  created_at: string;
  id: string;
  task_id: string;
  updated_at: string;
  user_id: string;
  task?: Task | null;
  user?: Profile | null;
}

export interface Task {
  assigned_to: string | null;
  attachments: unknown | null;
  category: string | null;
  company_id: string | null;
  completed_at: string | null;
  created_at: string;
  created_by: string;
  cycle_id: string | null;
  department_id: string | null;
  description: string | null;
  due_date: string | null;
  id: string;
  is_archived: boolean | null;
  parent_id: string | null;
  priority: TaskPriority;
  sort_order: number | null;
  start_date: string | null;
  status: TaskStatus;
  tags: string[] | null;
  title: string;
  updated_at: string;
  cycle?: Cycle | null;
  assignee?: Profile | null;
  company?: Company | null;
  creator?: Profile | null;
  department?: Department | null;
  parent?: Task | null;
}

export interface TaskAttachment {
  url: string;
  type: "IMAGE" | "PDF" | "DOC" | "EXCEL" | "OTHER";
  name?: string;
  uploaded_at?: string;
}